Repository CommuteCompanion/etsn05-project, pull requests merged in 2018-10, with the labels that each got.

#80 Add method to get all drives as Admin
  src/main/java/se/lth/base/server/data/DriveDataAccess.java
  src/main/java/se/lth/base/server/rest/DriveResource.java
  src/main/resources/se/lth/base/server/database/schema.sql
  src/test/java/se/lth/base/server/rest/DriveResourceTest.java
Labels: backend, bugfix, feature

#87 Feature/#27 #28 drive and search
  src/main/resources/webassets/js/custom/drive.js
  src/main/resources/webassets/js/custom/search.js
  src/main/resources/webassets/scss/custom/main.scss
  src/main/resources/webassets/templates/drive.html
  src/main/resources/webassets/templates/search.html
Labels: feature, frontend

#106 Feature/#29 commutes page
  src/main/resources/webassets/index.html
  src/main/resources/webassets/js/custom/index.js
  src/main/resources/webassets/js/custom/templates/my-commutes.js
  src/main/resources/webassets/scss/custom/main.scss
  src/main/resources/webassets/templates/my-commutes.html
  src/main/resources/webassets/templates/search.html
Labels: feature, frontend

#105 Remove username and replace with email
  src/main/java/se/lth/base/server/data/Credentials.java
  src/main/java/se/lth/base/server/data/User.java
  src/main/java/se/lth/base/server/data/UserDataAccess.java
  src/main/java/se/lth/base/server/mail/CustomEmail.java
  src/main/resources/se/lth/base/server/database/schema.sql
  src/main/resources/webassets/index.html
  src/main/resources/webassets/js/custom/index.js
  src/main/resources/webassets/js/custom/login.js
  src/main/resources/webassets/js/custom/register.js
  src/main/resources/webassets/js/custom/rest.js
  src/main/resources/webassets/login.html
  src/main/resources/webassets/register.html
  src/main/resources/webassets/spec/index-spec.js
  src/main/resources/webassets/spec/login-spec.js
  src/main/resources/webassets/templates/user-profile.html
  src/test/java/se/lth/base/server/BaseResourceTest.java
  src/test/java/se/lth/base/server/data/UserDataAccessTest.java
  src/test/java/se/lth/base/server/database/BaseDataAccessTest.java
  src/test/java/se/lth/base/server/rest/UserResourceTest.java
Labels: backend, bugfix, frontend

#113 Bugfix/#107 dynamic modals
  src/main/resources/webassets/index.html
  src/main/resources/webassets/js/custom/templates/my-commutes.js
  src/main/resources/webassets/templates/my-commutes.html
Labels: bugfix, frontend

#120 Rest method to get all drives with reports
  src/main/java/se/lth/base/server/data/DriveDataAccess.java
  src/main/java/se/lth/base/server/rest/DriveResource.java
Labels: backend, feature

#126 Updated users in db according to SVVI
  src/main/resources/se/lth/base/server/database/schema.sql
  src/test/java/se/lth/base/server/BaseResourceTest.java
  src/test/java/se/lth/base/server/database/BaseDataAccessTest.java
Labels: feature

#116 Only count accepted accepted users when counting passengers
  src/main/java/se/lth/base/server/data/DriveUserDataAccess.java
  src/main/java/se/lth/base/server/rest/DriveResource.java
Labels: backend, bugfix

#157 changed getDrivesForUser so it returns DriveWraps
  src/main/java/se/lth/base/server/rest/DriveResource.java
  src/test/java/se/lth/base/server/rest/DriveResourceTest.java
Labels: backend, bugfix

#162 fixed the updateDrive test
  src/main/java/se/lth/base/server/data/DriveDataAccess.java
  src/test/java/se/lth/base/server/data/DriveDataAccessTest.java
Labels: backend, bugfix

#182 bugfix on getReportedDrives
  src/main/java/se/lth/base/server/data/DriveDataAccess.java
Labels: backend, bugfix

#185 Added tests for creating, deleting and updating drive
  src/test/java/se/lth/base/server/rest/DriveResourceTest.java
Labels: backend, feature

#193 add tests in driveresource
  src/main/java/se/lth/base/server/data/DriveUserDataAccess.java
  src/main/java/se/lth/base/server/rest/DriveResource.java
  src/test/java/se/lth/base/server/data/DriveDataAccessTest.java
  src/test/java/se/lth/base/server/rest/DriveResourceTest.java
Labels: backend, bugfix, feature

#224 Rating functionality
  src/main/java/se/lth/base/server/data/DriveRating.java
  src/main/java/se/lth/base/server/data/DriveRatingWrap.java
  src/main/java/se/lth/base/server/data/UserDataAccess.java
  src/main/java/se/lth/base/server/rest/DriveResource.java
  src/test/java/se/lth/base/server/data/UserDataAccessTest.java
  src/test/java/se/lth/base/server/rest/DriveResourceTest.java
Labels: backend, feature

#233 changed all licence to license
  src/main/java/se/lth/base/server/data/Credentials.java
  src/main/java/se/lth/base/server/data/User.java
  src/main/java/se/lth/base/server/data/UserDataAccess.java
  src/main/resources/webassets/js/custom/register.js
  src/main/resources/webassets/js/custom/rest.js
  src/main/resources/webassets/js/custom/templates/create-drive.js
  src/main/resources/webassets/js/custom/templates/user-profile.js
  src/main/resources/webassets/templates/create-drive.html
  src/main/resources/webassets/templates/user-profile.html
Labels: bugfix

#325 No longer possible to create drive before today
  src/main/java/se/lth/base/server/rest/DriveResource.java
  src/test/java/se/lth/base/server/rest/DriveResourceTest.java
Labels: backend, bugfix

#340 Correct format is now needed when setting times when creating a drive
  src/main/resources/webassets/js/custom/templates/edit-drive.js
  src/main/resources/webassets/templates/edit-drive.html
Labels: feature, frontend

#348 fixed the way drives are updated
  src/main/java/se/lth/base/server/data/DriveMilestone.java
  src/main/java/se/lth/base/server/rest/DriveResource.java
Labels: backend, bugfix
